export const masVistos = {
  status: "OK",
  copyright:
    "Copyright (c) 2024 The New York Times Company.  All Rights Reserved.",
  num_results: 20,
  results: [
    {
      uri: "nyt://article/0b302102-815e-58f5-b8eb-d8da133ee40b",
      url: "https://www.nytimes.com/2024/03/09/world/middleeast/yazan-kafarneh-gaza-starvation.html",
      id: 100000009346425,
      asset_id: 100000009346425,
      source: "New York Times",
      published_date: "2024-03-09",
      updated: "2024-03-10 16:26:32",
      section: "World",
      subsection: "Middle East",
      nytdsection: "world",
      adx_keywords:
        "Israel-Gaza War (2023- );Palestinians;Famine;Malnutrition;Children and Childhood;International Relations;Kafarneh, Yazan;Gaza Strip;Israel",
      column: null,
      byline: "By Bilal Shbair, Vivian Yee and Aaron Boxerman",
      type: "Article",
      title:
        "The 10-Year-Old Boy Who Has Become the Face of Starvation in Gaza",
      abstract:
        "The harrowing image of a skeletal Yazan Kafarneh circulated widely on social media and has served as a graphic warning about the enclave’s dire food situation.",
      des_facet: [
        "Israel-Gaza War (2023- )",
        "Palestinians",
        "Famine",
        "Malnutrition",
        "Children and Childhood",
        "International Relations",
      ],
      org_facet: [],
      per_facet: ["Kafarneh, Yazan"],
      geo_facet: ["Gaza Strip", "Israel"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Humanitarian aid dropped by U.S. aircraft over the northern Gaza Strip on Thursday.",
          copyright: "Mohammed Saber/EPA, via Shutterstock",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/03/08/multimedia/08gaza-hunger-child-02-phjw/08gaza-hunger-child-02-phjw-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/08/multimedia/08gaza-hunger-child-02-phjw/08gaza-hunger-child-02-phjw-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/08/multimedia/08gaza-hunger-child-02-phjw/08gaza-hunger-child-02-phjw-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/d10b7f34-cc49-5102-8310-6ac063f931a6",
      url: "https://www.nytimes.com/2024/03/10/style/oscars-red-carpet-photos.html",
      id: 100000009342631,
      asset_id: 100000009342631,
      source: "New York Times",
      published_date: "2024-03-10",
      updated: "2024-03-11 00:00:07",
      section: "Style",
      subsection: "",
      nytdsection: "style",
      adx_keywords:
        "Academy Awards (Oscars);Movies;Fashion and Apparel;vis-photo",
      column: null,
      byline: "By The Styles Desk",
      type: "Article",
      title: "Oscars Red Carpet 2024: See the Stars’ Arrival Looks",
      abstract:
        "Ryan Gosling, Margot Robbie, Ariana Grande and other nominees, presenters and performers made their entrances for the 96th Academy Awards in season-defining style.",
      des_facet: [
        "Academy Awards (Oscars)",
        "Movies",
        "Fashion and Apparel",
        "vis-photo",
      ],
      org_facet: [],
      per_facet: [],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "Zendaya, one of the ceremony’s presenters, in Armani.",
          copyright: "Jutharat Pinyodoonyachet for The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/03/10/fashion/poupay-oscars-2024-2842-zendaya-Toned/poupay-oscars-2024-2842-zendaya-thumbStandard-v4.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/10/fashion/poupay-oscars-2024-2842-zendaya-Toned/poupay-oscars-2024-2842-zendaya-mediumThreeByTwo210-v3.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/10/fashion/poupay-oscars-2024-2842-zendaya-Toned/poupay-oscars-2024-2842-zendaya-mediumThreeByTwo440-v3.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/c73b97b6-2de3-5c50-9d72-f6123b75fff2",
      url: "https://www.nytimes.com/2024/03/10/world/europe/princess-kate-middleton-surgery-photo.html",
      id: 100000009352600,
      asset_id: 100000009352600,
      source: "New York Times",
      published_date: "2024-03-10",
      updated: "2024-03-10 21:23:32",
      section: "World",
      subsection: "Europe",
      nytdsection: "world",
      adx_keywords:
        "Royal Families;Mother's Day;Surgery and Surgeons;Rumors and Misinformation;Catherine, Princess of Wales;Kensington Palace;Great Britain",
      column: null,
      byline: "By Mark Landler",
      type: "Article",
      title: "Palace Releases Photo of Catherine, Two Months After Her Surgery",
      abstract:
        "Amid rampant rumors on social media about the condition of the princess, Kensington Palace issued the picture to mark Mother’s Day in Britain. But questions were later raised about the photo.",
      des_facet: [
        "Royal Families",
        "Mother's Day",
        "Surgery and Surgeons",
        "Rumors and Misinformation",
      ],
      org_facet: ["Kensington Palace"],
      per_facet: ["Catherine, Princess of Wales"],
      geo_facet: ["Great Britain"],
      media: [],
      eta_id: 0,
    },
    {
      uri: "nyt://interactive/2bf39e01-3e1b-51eb-b979-dd6d5693568f",
      url: "https://www.nytimes.com/interactive/2024/03/10/magazine/jeremy-strong-interview.html",
      id: 100000009348954,
      asset_id: 100000009348954,
      source: "New York Times",
      published_date: "2024-03-10",
      updated: "2024-03-10 08:44:12",
      section: "Magazine",
      subsection: "",
      nytdsection: "magazine",
      adx_keywords:
        "Actors and Actresses;Content Type: Personal Profile;Strong, Jeremy (1978- )",
      column: null,
      byline: "By David Marchese",
      type: "Interactive",
      title: "Jeremy Strong Isn’t Sure He Knows Who He Is",
      abstract:
        "After “Succession,” says the actor, “I felt a profound sense of, Was this the event of my life?”",
      des_facet: ["Actors and Actresses", "Content Type: Personal Profile"],
      org_facet: [],
      per_facet: ["Strong, Jeremy (1978- )"],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "",
          caption: "",
          copyright: "Mamadi Doumbouya for The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/03/17/magazine/17mag-talk/17mag-talk-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/17/magazine/17mag-talk/17mag-talk-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/17/magazine/17mag-talk/17mag-talk-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/ec12d1f6-3642-5865-9712-043e8eedb7ff",
      url: "https://www.nytimes.com/2024/01/23/movies/2024-oscar-nominees-list.html",
      id: 100000009267814,
      asset_id: 100000009267814,
      source: "New York Times",
      published_date: "2024-01-23",
      updated: "2024-03-10 16:36:00",
      section: "Movies",
      subsection: "",
      nytdsection: "movies",
      adx_keywords: "Academy Awards (Oscars)",
      column: null,
      byline: "By Shivani Gonzalez",
      type: "Article",
      title: "Oscar Nominees 2024: See the Full List",
      abstract: "The complete list of Academy Award nominees for 2024.",
      des_facet: ["Academy Awards (Oscars)"],
      org_facet: [],
      per_facet: [],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "Cillian Murphy in “Oppenheimer.”",
          copyright: "Universal Pictures",
          approved_for_syndication: 0,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/01/23/multimedia/23oscars-list-tglz/23oscars-list-tglz-thumbStandard-v2.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/01/23/multimedia/23oscars-list-tglz/23oscars-list-tglz-mediumThreeByTwo210-v2.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/01/23/multimedia/23oscars-list-tglz/23oscars-list-tglz-mediumThreeByTwo440-v2.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/9c4c97a0-0509-55df-802c-cb7c87c68735",
      url: "https://www.nytimes.com/2024/03/10/opinion/trump-republicans-mcconnell-2024.html",
      id: 100000009349243,
      asset_id: 100000009349243,
      source: "New York Times",
      published_date: "2024-03-10",
      updated: "2024-03-10 09:00:18",
      section: "Opinion",
      subsection: "",
      nytdsection: "opinion",
      adx_keywords:
        "United States Politics and Government;Presidential Election of 2024;Conservatism (US Politics);Storming of the US Capitol (Jan, 2021);Haley, Nikki R;Trump, Donald J;Republican Party;House of Representatives;Senate",
      column: null,
      byline: "By Peter Wehner",
      type: "Article",
      title: "If There’s One Thing Trump Is Right About, It’s Republicans",
      abstract:
        "For the thousandth time, the G.O.P. refused an off-ramp that would free itself from him.",
      des_facet: [
        "United States Politics and Government",
        "Presidential Election of 2024",
        "Conservatism (US Politics)",
        "Storming of the US Capitol (Jan, 2021)",
      ],
      org_facet: ["Republican Party", "House of Representatives", "Senate"],
      per_facet: ["Haley, Nikki R", "Trump, Donald J"],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Mike Osborne for The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/03/10/multimedia/10wehner-fwjh/10wehner-fwjh-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/10/multimedia/10wehner-fwjh/10wehner-fwjh-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/10/multimedia/10wehner-fwjh/10wehner-fwjh-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/d4d48eb8-8390-530b-bce0-d86b6faf2f09",
      url: "https://www.nytimes.com/2024/03/09/us/politics/katie-britt-republican-response-sotu-border.html",
      id: 100000009352256,
      asset_id: 100000009352256,
      source: "New York Times",
      published_date: "2024-03-09",
      updated: "2024-03-10 22:59:17",
      section: "U.S.",
      subsection: "Politics",
      nytdsection: "u.s.",
      adx_keywords:
        "Rumors and Misinformation;State of the Union Message (US);United States Politics and Government;Britt, Katie (1982- );Biden, Joseph R Jr;Republican Party;Senate",
      column: null,
      byline: "By Ken Bensinger",
      type: "Article",
      title:
        "Britt Tells Misleading Border Story in State of the Union Response",
      abstract:
        "The Alabama senator used a story about sex trafficking to criticize the Biden administration’s border policies. But the events occurred in Mexico years ago.",
      des_facet: [
        "Rumors and Misinformation",
        "State of the Union Message (US)",
        "United States Politics and Government",
      ],
      org_facet: ["Republican Party", "Senate"],
      per_facet: ["Britt, Katie (1982- )", "Biden, Joseph R Jr"],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Katie Britt, a first-term senator from Alabama, delivered the Republican response to President Biden’s State of the Union address.",
          copyright: "Haiyun Jiang for The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/03/09/multimedia/09pol-swiper-britt-sotu-zbkf/09pol-swiper-britt-sotu-zbkf-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/09/multimedia/09pol-swiper-britt-sotu-zbkf/09pol-swiper-britt-sotu-zbkf-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/09/multimedia/09pol-swiper-britt-sotu-zbkf/09pol-swiper-britt-sotu-zbkf-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/e46e4444-bdda-5eb1-8eef-e5a9ce062226",
      url: "https://www.nytimes.com/2024/03/09/us/politics/us-military-gaza-aid.html",
      id: 100000009343814,
      asset_id: 100000009343814,
      source: "New York Times",
      published_date: "2024-03-09",
      updated: "2024-03-10 22:47:43",
      section: "U.S.",
      subsection: "Politics",
      nytdsection: "u.s.",
      adx_keywords:
        "Israel-Gaza War (2023- );United States Defense and Military Forces;Humanitarian Aid;Foreign Aid;Andres, Jose (1969- );Army Corps of Engineers;United States Army;Israel;Gaza Strip",
      column: null,
      byline: "By Helene Cooper and Eric Schmitt",
      type: "Article",
      title: "U.S. Military Enters a New Phase With Gaza Aid Operations",
      abstract:
        "As the United States continues providing Israel with munitions, the Pentagon will deliver food and other assistance to Gazans by sea and air.",
      des_facet: [
        "Israel-Gaza War (2023- )",
        "United States Defense and Military Forces",
        "Humanitarian Aid",
        "Foreign Aid",
      ],
      org_facet: ["Army Corps of Engineers", "United States Army"],
      per_facet: ["Andres, Jose (1969- )"],
      geo_facet: ["Israel", "Gaza Strip"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "The U.S. military has built floating causeways like this one off the coast of Australia for troops to cross rivers, unload supplies and conduct other military operations. ",
          copyright:
            "U.S. Army Photo by Sgt. Ashunteia’ Smith, 16th Combat Aviation Brigade",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/03/09/lens/09-DC-MILITARY-AID/09-DC-MILITARY-AID-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/09/lens/09-DC-MILITARY-AID/09-DC-MILITARY-AID-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/09/lens/09-DC-MILITARY-AID/09-DC-MILITARY-AID-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/10b01cbd-e7c8-5c69-aebd-4edcd2f11477",
      url: "https://www.nytimes.com/2024/03/09/style/alyssa-farah-griffin-trump-cnn.html",
      id: 100000009349995,
      asset_id: 100000009349995,
      source: "New York Times",
      published_date: "2024-03-09",
      updated: "2024-03-09 20:54:24",
      section: "Style",
      subsection: "",
      nytdsection: "style",
      adx_keywords:
        "Television;News and News Media;Presidential Election of 2024;United States Politics and Government;Content Type: Personal Profile;Right-Wing Extremism and Alt-Right;Farah, Alyssa;Trump, Donald J;CNN;ABC Inc;Republican Party",
      column: null,
      byline: "By Jacob Bernstein",
      type: "Article",
      title: "A Former Trump Aide Becomes a Liberal Favorite",
      abstract:
        "After breaking with her onetime boss, Alyssa Farah Griffin finds a warm welcome on “The View” and CNN.",
      des_facet: [
        "Television",
        "News and News Media",
        "Presidential Election of 2024",
        "United States Politics and Government",
        "Content Type: Personal Profile",
        "Right-Wing Extremism and Alt-Right",
      ],
      org_facet: ["CNN", "ABC Inc", "Republican Party"],
      per_facet: ["Farah, Alyssa", "Trump, Donald J"],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Alyssa Farah Griffin, backstage at ABC Studios in Manhattan shortly before a recent taping of “The View.”",
          copyright: "Lanna Apisukh for The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/03/09/multimedia/09GRIFFIN-hqlg/09GRIFFIN-hqlg-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/09/multimedia/09GRIFFIN-hqlg/09GRIFFIN-hqlg-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/09/multimedia/09GRIFFIN-hqlg/09GRIFFIN-hqlg-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/7a5c3920-caf8-5ded-a560-ad4f5a393d9e",
      url: "https://www.nytimes.com/2024/03/10/us/politics/katie-britt-sotu-response-border.html",
      id: 100000009352717,
      asset_id: 100000009352717,
      source: "New York Times",
      published_date: "2024-03-10",
      updated: "2024-03-10 14:02:26",
      section: "U.S.",
      subsection: "Politics",
      nytdsection: "u.s.",
      adx_keywords:
        "United States Politics and Government;Human Trafficking;State of the Union Message (US);Britt, Katie (1982- );Fox News Channel",
      column: null,
      byline: "By Maggie Astor",
      type: "Article",
      title:
        "Amid Criticism, Britt Seeks to Defend Her Misleading Border Comments",
      abstract:
        "Katie Britt, a Republican senator from Alabama, suggested on Fox News that viewers should have parsed her wording to determine that a sex-trafficking case she referred to wasn’t recent.",
      des_facet: [
        "United States Politics and Government",
        "Human Trafficking",
        "State of the Union Message (US)",
      ],
      org_facet: ["Fox News Channel"],
      per_facet: ["Britt, Katie (1982- )"],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "“I very clearly said I spoke to a woman who told me about when she was trafficked when she was 12,” said Senator Katie Britt.",
          copyright: "Anna Moneymaker/Getty Images",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/03/10/multimedia/10pol-swiper-britt-bkpq/10pol-swiper-britt-bkpq-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/10/multimedia/10pol-swiper-britt-bkpq/10pol-swiper-britt-bkpq-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/10/multimedia/10pol-swiper-britt-bkpq/10pol-swiper-britt-bkpq-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/aa704682-17c0-5504-a774-20a488872670",
      url: "https://www.nytimes.com/2024/03/10/science/ai-learning-biology.html",
      id: 100000009296930,
      asset_id: 100000009296930,
      source: "New York Times",
      published_date: "2024-03-10",
      updated: "2024-03-10 08:12:43",
      section: "Science",
      subsection: "",
      nytdsection: "science",
      adx_keywords:
        "your-feed-science;Artificial Intelligence;Biology and Biochemistry;Genetics and Heredity;Computers and the Internet;Research;DNA (Deoxyribonucleic Acid);Science and Technology;ChatGPT",
      column: null,
      byline: "By Carl Zimmer",
      type: "Article",
      title: "A.I. Is Learning What It Means to Be Alive",
      abstract:
        "Given troves of data about genes and cells, A.I. models have made some surprising discoveries. What could they teach us someday?",
      des_facet: [
        "your-feed-science",
        "Artificial Intelligence",
        "Biology and Biochemistry",
        "Genetics and Heredity",
        "Computers and the Internet",
        "Research",
        "DNA (Deoxyribonucleic Acid)",
        "Science and Technology",
        "ChatGPT",
      ],
      org_facet: [],
      per_facet: [],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Doug Chayka",
          approved_for_syndication: 0,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/03/12/science/00AI-biology-03/00AI-biology-03-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/12/science/00AI-biology-03/00AI-biology-03-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/12/science/00AI-biology-03/00AI-biology-03-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/834da44f-1dc3-5089-900b-fd8c3a78e995",
      url: "https://www.nytimes.com/2024/03/10/nyregion/letitia-james-trump-nra.html",
      id: 100000009336350,
      asset_id: 100000009336350,
      source: "New York Times",
      published_date: "2024-03-10",
      updated: "2024-03-10 23:12:40",
      section: "New York",
      subsection: "",
      nytdsection: "new york",
      adx_keywords:
        "New York State Civil Case Against Trump (452564/2022);United States Politics and Government;Decisions and Verdicts;Attorneys General;Elections, Attorneys General;James, Letitia;Stefanik, Elise;City Council (NYC);Manhattan (NYC)",
      column: null,
      byline: "By Jesse McKinley",
      type: "Article",
      title:
        "After Letitia James Wins Big in Courtrooms, She Celebrates in Public",
      abstract:
        "Prevailing over former President Donald J. Trump and the National Rifle Association makes an elected Democrat a lightning rod. Foes call her vindictive. Allies say she’s just doing her job.",
      des_facet: [
        "New York State Civil Case Against Trump (452564/2022)",
        "United States Politics and Government",
        "Decisions and Verdicts",
        "Attorneys General",
        "Elections, Attorneys General",
      ],
      org_facet: ["City Council (NYC)"],
      per_facet: ["James, Letitia", "Stefanik, Elise"],
      geo_facet: ["Manhattan (NYC)"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Letitia James has needled those she vanquished on social media, angering opponents.",
          copyright: "Doug Mills/The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/03/06/multimedia/00ny-james-tcjv/00ny-james-tcjv-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/06/multimedia/00ny-james-tcjv/00ny-james-tcjv-mediumThreeByTwo210-v3.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/06/multimedia/00ny-james-tcjv/00ny-james-tcjv-mediumThreeByTwo440-v3.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/33ad7903-5972-5d10-807d-d03785367eb0",
      url: "https://www.nytimes.com/2024/03/07/well/live/daylight-savings-time-sleep.html",
      id: 100000009335056,
      asset_id: 100000009335056,
      source: "New York Times",
      published_date: "2024-03-07",
      updated: "2024-03-08 12:25:58",
      section: "Well",
      subsection: "Live",
      nytdsection: "well",
      adx_keywords:
        "Daylight Saving Time;Content Type: Service;Watches and Clocks;Sleep;Spring (Season)",
      column: null,
      byline: "By Alice Callahan",
      type: "Article",
      title: "Don’t Let Daylight Saving Time Ruin Your Sleep",
      abstract:
        "Here’s how to feel well rested when the clocks spring forward on Sunday.",
      des_facet: [
        "Daylight Saving Time",
        "Content Type: Service",
        "Watches and Clocks",
        "Sleep",
        "Spring (Season)",
      ],
      org_facet: [],
      per_facet: [],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "María Medem",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/03/05/well/WELL-DST-SLEEP/WELL-DST-SLEEP-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/05/well/WELL-DST-SLEEP/WELL-DST-SLEEP-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/05/well/WELL-DST-SLEEP/WELL-DST-SLEEP-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/b9cf7678-d437-5aaf-82e1-e99b61ebfba8",
      url: "https://www.nytimes.com/2024/03/09/business/bmw-electric-vehicles.html",
      id: 100000009338024,
      asset_id: 100000009338024,
      source: "New York Times",
      published_date: "2024-03-09",
      updated: "2024-03-09 14:41:16",
      section: "Business",
      subsection: "",
      nytdsection: "business",
      adx_keywords:
        "Automobiles;Electric and Hybrid Vehicles;Factories and Manufacturing;Batteries;Driverless and Semiautonomous Vehicles;Bayerische Motorenwerke AG;Tesla Motors Inc;Munich (Germany)",
      column: null,
      byline: "By Jack Ewing",
      type: "Article",
      title: "BMW Is a Surprise Winner in Electric Vehicles",
      abstract:
        "Once considered a laggard, the German luxury carmaker is one of only a few established automakers that has been able to compete effectively against Tesla.",
      des_facet: [
        "Automobiles",
        "Electric and Hybrid Vehicles",
        "Factories and Manufacturing",
        "Batteries",
        "Driverless and Semiautonomous Vehicles",
      ],
      org_facet: ["Bayerische Motorenwerke AG", "Tesla Motors Inc"],
      per_facet: [],
      geo_facet: ["Munich (Germany)"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Employees conducting inspections of electric vehicles at BMW’s plant in Munich.",
          copyright: "Laetitia Vancon for The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/03/13/multimedia/00bmw-electric-01-mhtc/00bmw-electric-01-mhtc-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/13/multimedia/00bmw-electric-01-mhtc/00bmw-electric-01-mhtc-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/13/multimedia/00bmw-electric-01-mhtc/00bmw-electric-01-mhtc-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/2319f4a7-dc4d-5419-bb43-96ee60377773",
      url: "https://www.nytimes.com/2024/03/10/arts/television/saturday-night-live-scarlett-johansson.html",
      id: 100000009352557,
      asset_id: 100000009352557,
      source: "New York Times",
      published_date: "2024-03-10",
      updated: "2024-03-10 05:20:31",
      section: "Arts",
      subsection: "Television",
      nytdsection: "arts",
      adx_keywords:
        "State of the Union Message (US);Johansson, Scarlett;Brolin, Josh;Grande, Ariana",
      column: null,
      byline: "By Dave Itzkoff",
      type: "Article",
      title:
        "‘Saturday Night Live’ Feasts on the Bounty of the State of the Union",
      abstract:
        "The Republican rebuttal delivered by Senator Katie Britt already struck many viewers as parody, making Scarlett Johansson’s job look easy.",
      des_facet: ["State of the Union Message (US)"],
      org_facet: [],
      per_facet: ["Johansson, Scarlett", "Brolin, Josh", "Grande, Ariana"],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Scarlett Johansson as Senator Katie Britt. “Tonight,” she said, “I’ll be auditioning for the part of scary mom.”",
          copyright: "NBC Universal, via YouTube",
          approved_for_syndication: 0,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/03/10/world/10snl/10snl-thumbStandard.png",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/10/world/10snl/10snl-mediumThreeByTwo210.png",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/10/world/10snl/10snl-mediumThreeByTwo440.png",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/429e93b4-8ea0-549f-95c4-27d56b2b78e6",
      url: "https://www.nytimes.com/2024/03/10/movies/oscars-winners-list.html",
      id: 100000009347663,
      asset_id: 100000009347663,
      source: "New York Times",
      published_date: "2024-03-10",
      updated: "2024-03-11 00:32:37",
      section: "Movies",
      subsection: "",
      nytdsection: "movies",
      adx_keywords: "Movies;Academy Awards (Oscars)",
      column: null,
      byline: "By Shivani Gonzalez",
      type: "Article",
      title: "Oscars 2024 Winners: See the Full List",
      abstract: "The complete list of winners for the 96th Academy Awards.",
      des_facet: ["Movies", "Academy Awards (Oscars)"],
      org_facet: [],
      per_facet: [],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Da’Vine Joy Randolph accepting her award for best supporting actress for her role in “The Holdovers.”",
          copyright: "Amir Hamja/The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/03/10/multimedia/10oscars-winners-list-davine/10oscars-winners-list-davine-thumbStandard-v2.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/10/multimedia/10oscars-winners-list-davine/10oscars-winners-list-davine-mediumThreeByTwo210-v2.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/10/multimedia/10oscars-winners-list-davine/10oscars-winners-list-davine-mediumThreeByTwo440-v2.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/eed2118b-35f0-5efc-9b01-c63004628e9c",
      url: "https://www.nytimes.com/2024/03/05/style/trader-joes-mini-tote.html",
      id: 100000009342224,
      asset_id: 100000009342224,
      source: "New York Times",
      published_date: "2024-03-05",
      updated: "2024-03-10 13:32:43",
      section: "Style",
      subsection: "",
      nytdsection: "style",
      adx_keywords:
        "Supermarkets and Grocery Stores;Handbags and Purses;Social Media;Trader Joe's;TikTok (ByteDance)",
      column: null,
      byline: "By Madison Malone Kircher",
      type: "Article",
      title: "Why Is This $2.99 Tote Bag Causing Chaos?",
      abstract:
        "It’s tiny. It’s cheap. Trader Joe’s stores can’t seem to keep them on shelves.",
      des_facet: [
        "Supermarkets and Grocery Stores",
        "Handbags and Purses",
        "Social Media",
      ],
      org_facet: ["Trader Joe's", "TikTok (ByteDance)"],
      per_facet: [],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Thaddeus Yan, a 23-year-old in Los Angeles, got his hands on a few of the coveted tote bags after visiting eight different stores.",
          copyright: "Thaddeus Yan",
          approved_for_syndication: 0,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/03/10/fashion/TRADERJOES-MINI/TRADERJOES-MINI-thumbStandard-v2.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/10/fashion/TRADERJOES-MINI/TRADERJOES-MINI-mediumThreeByTwo210-v3.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/10/fashion/TRADERJOES-MINI/TRADERJOES-MINI-mediumThreeByTwo440-v3.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/d0e6712d-b589-5efb-95b1-62d89da881d8",
      url: "https://www.nytimes.com/2024/03/08/style/erika-amundson-eli-newell-wedding.html",
      id: 100000009338898,
      asset_id: 100000009338898,
      source: "New York Times",
      published_date: "2024-03-08",
      updated: "2024-03-09 06:51:35",
      section: "Style",
      subsection: "",
      nytdsection: "style",
      adx_keywords: "Weddings and Engagements",
      column: null,
      byline: "By Tammy LaGorce",
      type: "Article",
      title:
        "A Wedding Do-Over After a Broken Heart (Not the Kind You’re Thinking)",
      abstract:
        "Just minutes after Eli Newell and Dr. Erika Amundson exchanged vows last spring, he was rushed to the hospital. Their second go-round was far less traumatic.",
      des_facet: ["Weddings and Engagements"],
      org_facet: [],
      per_facet: [],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Eli Newell and Dr. Erika Amundson, who were legally married last May before Mr. Newell was rushed to the hospital, held a wedding celebration Feb. 23 at the Grass Room in Los Angeles.",
          copyright: "EJD Photo",
          approved_for_syndication: 0,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/03/10/multimedia/08VOWS-OPEN-HEART-01-kbpj/08VOWS-OPEN-HEART-01-kbpj-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/10/multimedia/08VOWS-OPEN-HEART-01-kbpj/08VOWS-OPEN-HEART-01-kbpj-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/10/multimedia/08VOWS-OPEN-HEART-01-kbpj/08VOWS-OPEN-HEART-01-kbpj-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/9c8523f4-0a4f-5845-858f-8fd8671d1d3b",
      url: "https://www.nytimes.com/2024/03/08/movies/oscar-snubs-history.html",
      id: 100000009317476,
      asset_id: 100000009317476,
      source: "New York Times",
      published_date: "2024-03-08",
      updated: "2024-03-10 17:28:11",
      section: "Movies",
      subsection: "",
      nytdsection: "movies",
      adx_keywords:
        "Movies;Academy Awards (Oscars);Actors and Actresses;Affleck, Ben;Bacall, Lauren;Carrey, Jim;Chaplin, Charlie;Close, Glenn;Gerwig, Greta;Goldberg, Whoopi;Hitchcock, Alfred;Winfrey, Oprah;Washington, Denzel;Streisand, Barbra;Scorsese, Martin;Sandler, Adam;Oyelowo, David;Kubrick, Stanley;Lopez, Jennifer;Monroe, Marilyn",
      column: null,
      byline: "By The New York Times",
      type: "Article",
      title: "Spurned, Slighted, Rejected: 25 Oscar Snubs We’ll Never Get Over",
      abstract:
        "Greta Gerwig, you’re not alone. These artists and films memorably — outrageously in our view — got the brush-off from the academy. We’re still in disbelief.",
      des_facet: ["Movies", "Academy Awards (Oscars)", "Actors and Actresses"],
      org_facet: [],
      per_facet: [
        "Affleck, Ben",
        "Bacall, Lauren",
        "Carrey, Jim",
        "Chaplin, Charlie",
        "Close, Glenn",
        "Gerwig, Greta",
        "Goldberg, Whoopi",
        "Hitchcock, Alfred",
        "Winfrey, Oprah",
        "Washington, Denzel",
        "Streisand, Barbra",
        "Scorsese, Martin",
        "Sandler, Adam",
        "Oyelowo, David",
        "Kubrick, Stanley",
        "Lopez, Jennifer",
        "Monroe, Marilyn",
      ],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "James Kerr / Scorpion Dagger",
          approved_for_syndication: 0,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/03/10/autossell/10oscar-snubs/10oscar-snubs-thumbStandard-v2.png",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/10/autossell/10oscar-snubs/10oscar-snubs-mediumThreeByTwo210.png",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/10/autossell/10oscar-snubs/10oscar-snubs-mediumThreeByTwo440.png",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/6a0f36fe-9a03-55ed-b964-f72782bcff7e",
      url: "https://www.nytimes.com/2024/03/10/us/elon-musk-charity.html",
      id: 100000009309666,
      asset_id: 100000009309666,
      source: "New York Times",
      published_date: "2024-03-10",
      updated: "2024-03-10 12:47:06",
      section: "U.S.",
      subsection: "",
      nytdsection: "u.s.",
      adx_keywords:
        "Philanthropy;Tax Credits, Deductions and Exemptions;Tax Shelters;Stock Options and Purchase Plans;Musk, Elon;Space Exploration Technologies Corp;Tesla Motors Inc;Boring Company;Musk Foundation;Boca Chica (Tex);Brownsville (Tex)",
      column: null,
      byline: "By David A. Fahrenthold and Ryan Mac",
      type: "Article",
      title: "Elon Musk Has a Giant Charity. Its Money Stays Close to Home.",
      abstract:
        "After making billions in tax-deductible donations to his philanthropy, the owner of Tesla and SpaceX gave away far less than required in some years — and what he did give often supported his own interests.",
      des_facet: [
        "Philanthropy",
        "Tax Credits, Deductions and Exemptions",
        "Tax Shelters",
        "Stock Options and Purchase Plans",
      ],
      org_facet: [
        "Space Exploration Technologies Corp",
        "Tesla Motors Inc",
        "Boring Company",
        "Musk Foundation",
      ],
      per_facet: ["Musk, Elon"],
      geo_facet: ["Boca Chica (Tex)", "Brownsville (Tex)"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "The Rocket Bar is one of several new nightlife establishments that received funds from the Musk Foundation’s initiative to revitalize downtown Brownsville, Texas.",
          copyright: "Meridith Kohut for The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/03/07/multimedia/00dc-musk-charity-08-qbfh/00dc-musk-charity-08-qbfh-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/07/multimedia/00dc-musk-charity-08-qbfh/00dc-musk-charity-08-qbfh-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/03/07/multimedia/00dc-musk-charity-08-qbfh/00dc-musk-charity-08-qbfh-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
  ],
};
